{-
fizzbuzz.hs

Created by Yamato Matsuoka on 2013-07-03.

Challenge Description
------------------------
Players generally sit in a circle. The player designated to go first says the number "1", and each player thenceforth counts one number in turn. However, any number divisible by 'A' e.g. three is replaced by the word fizz and any divisible by 'B' e.g. five by the word buzz. Numbers divisible by both become fizz buzz. A player who hesitates or makes a mistake is either eliminated.

Write a program that prints out the the pattern generated by such a scenario given the values of 'A'/'B' and 'N' which are read from an input text file. The input text file contains three space delimited numbers i.e. A, B, N. The program should then print out the final series of numbers using 'F' for fizz, 'B' for 'buzz' and 'FB' for fizz buzz.

Input sample
-------------
Your program should read an input file (provided on the command line) which contains multiple newline separated lines. Each line will contain 3 numbers which are space delimited. The first number is first number to divide by ('A' in this example), the second number is the second number to divide by ('B' in this example) and the third number is where you should count till ('N' in this example). You may assume that the input file is formatted correctly and is the numbers are valid positive integers.e.g.
```
3 5 10
2 7 15
```

Output sample
--------------
Print out the series 1 through N replacing numbers divisible by 'A' by F, numbers divisible by 'B' by B and numbers divisible by both as 'FB'. Since the input file contains multiple sets of values, your output will print out one line per set. Ensure that there are no trailing empty spaces on each line you print.e.g.

```
1 2 F 4 B F 7 8 F B
1 F 3 F 5 F B F 9 F 11 F 13 FB 15
```
-}
import System.Environment (getArgs)

fizzbuzz :: Int -> Int -> Int -> [String]
fizzbuzz p q n = map (fizzbuzzHelper p q) [1 .. n]

fizzbuzzHelper :: Int -> Int -> Int -> String
fizzbuzzHelper p q i
    | i `mod` p == 0 && i `mod` q == 0 = "FB"
    | i `mod` p == 0                   = "F"
    | i `mod` q == 0                   = "B"
    | otherwise                        = show i

join :: Char -> [String] -> String
join c ws = foldr1 (\w s -> w ++ c : s) ws

main = do
    args <- getArgs
    let filename = head args
    contents <- readFile filename
    let inputs = [[read w | w <- (words line)] | line <- (lines contents)] :: [[Int]]
    let outputs = [fizzbuzz p q n| [p, q, n] <- inputs]
    let outputs' = map (join ' ') outputs
    mapM putStrLn outputs'

